import assert from 'node:assert/strict';
import { Room } from '../src/server/room.js';
import { MapBuilder } from '../src/shared/maps/builder.js';
import { GameMap } from '../src/shared/gamemap.js';
import { defaultLoadout, AIR_DEFENSE } from '../src/shared/weapons.js';
import { KEY, DT } from '../src/shared/constants.js';
import { updateAirLock, deployFlares, updateFlares, airThreat } from '../src/server/air-defense.js';
import { updateProjectiles } from '../src/server/projectiles.js';
import { useGadget } from '../src/server/gadgets.js';
import { enterVehicle, updateVehicles } from '../src/server/vehicles.js';
import { selectSlot } from '../src/server/combat.js';
const fake = () => ({ send() {}, sendRaw() {}, congested: () => false, leaveRoom() {} });
const room = new Room('AA QA', { map: 'riverside', mode: 'conquest', teamSize: 2, bots: false, vehicles: true }, null);
const p = room.addHuman(fake(), 'Engineer'), pilot = room.addHuman(fake(), 'Pilot'); room.assignTeam(p, 0); room.assignTeam(pilot, 1); room.start();
const g = room.game, mb = new MapBuilder(90, 90, '.'); mb.rect(1, 1, 3, 3, 't').rect(85, 85, 3, 3, 'c');
g.map = new GameMap({ id: 'air-defense', name: 'QA', ...mb.finish() });
for (const v of g.vehicles) v.map = g.map;
p.loadout = defaultLoadout('engineer'); p.loadout.gadgets[1] = 'stinger';
for (const q of [p, pilot]) { q.respawnAt = 0; g.deploy(q, { k: 'base', id: 0 }); q.spawnProt = 0; }
p.x = 400; p.y = 800; p.z = 0; p.sel = 'gadget1'; p.drawT = 0;
const heli = g.vehicles.find((v) => v.type === 'heli'); g.vehicles = [heli]; heli.x = 1100; heli.y = 800; heli.flightZ = 250; heli.team = 1;
enterVehicle(g, pilot, heli, 0);
let count = 0; const check = (v, msg) => { assert.ok(v, msg); count++; console.log('ok', msg); };
const aim = () => { p.angle = Math.atan2(heli.y - p.y, heli.x - p.x); p.pitch = Math.atan2(heli.z + 26 - p.eyeZ, Math.hypot(heli.x - p.x, heli.y - p.y)); };
const lock = () => { aim(); for (let i = 0; i < 90; i++) updateAirLock(g, p, true); };
aim(); useGadget(g, p, p.gadget(), true, true, 700, 64 | 16);
check(g.projectiles.length === 0 && p.gadget().loaded, 'Firing without a complete lock preserves the rocket');
lock(); check(p.lockTarget === heli.id && p.lockT === AIR_DEFENSE.lockTime, 'Visible elevated helicopter acquires a full 3D lock');
check(g.snapshotFor(p).me.lk[1] === 1 && g.snapshotFor(p).me.mv[3] === 1, 'Lock completion and launcher ADS reach the client');
check(airThreat(g, heli) === 'locking', 'Pilot receives acquisition warning');
p.pitch = -.4; updateAirLock(g, p, true); check(!p.lockTarget, 'Looking below the aircraft breaks lock');
lock(); g.applyCmd(p, KEY.SPRINT | KEY.UP, p.angle, 0, 700, undefined, undefined, p.pitch); check(!p.lockTarget, 'Sprinting away clears acquisition even when gadgets cannot fire');
lock(); updateAirLock(g, p, false); check(!p.lockTarget && !p.lockT, 'Releasing ADS resets acquisition');
heli.team = 0; lock(); check(!p.lockTarget, 'Friendly aircraft cannot be locked');
heli.team = -1; lock(); check(!p.lockTarget, 'Neutral aircraft cannot be locked');
heli.team = 1; heli.dead = true; lock(); check(!p.lockTarget, 'Wrecked aircraft cannot be locked'); heli.dead = false;
heli.x = 2850; lock(); check(!p.lockTarget, 'Aircraft outside 3D seeker range cannot be locked'); heli.x = 1100;
g.map.setTile(13, 25, '#'); lock(); check(!p.lockTarget, 'A solid wall blocks the rising seeker ray'); g.map.setTile(13, 25, '.');
g.smokes.push({ x: 750, y: 800, r: 50 }); lock(); check(!p.lockTarget, 'Smoke obscures the seeker'); g.smokes = [];
p.reloadT = 1; lock(); check(!p.lockTarget, 'Reloading cannot acquire a lock'); p.reloadT = 0;
lock(); const initialHp = heli.hp; useGadget(g, p, p.gadget(), true, true, 700, 64 | 16);
check(g.projectiles.length === 1 && g.projectiles[0].target === heli.id, 'A locked Stinger launches toward its aircraft');
check(!p.gadget().loaded && p.reloadT > 0 && !p.lockTarget, 'Firing consumes the chamber, starts reload and clears lock');
check(airThreat(g, heli) === 'incoming' && g.snapshotFor(pilot).me.veh.threat === 'incoming', 'Pilot snapshot distinguishes incoming missile from acquisition');
const missile = g.projectiles[0], z0 = missile.z; updateProjectiles(g, DT); check(missile.z > z0, 'Missile climbs toward actual aircraft altitude');
for (let i = 0; i < 240 && g.projectiles.length; i++) { heli.y += .35; updateProjectiles(g, DT); }
check(heli.hp < initialHp && g.projectiles.length === 0, 'Homing missile hits a moving elevated helicopter');
heli.hp = heli.def.hp; heli.dead = false; heli.y = 800; p.reloadT = p.fireCd = 0; p.gadget().loaded = true; lock();
useGadget(g, p, p.gadget(), true, true, 700, 64 | 16); const decoyShot = g.projectiles[0];
check(!deployFlares(g, p), 'Infantry cannot deploy helicopter flares');
pilot.seat = 1; check(!deployFlares(g, pilot), 'Gunner cannot deploy pilot countermeasures'); pilot.seat = 0;
check(deployFlares(g, pilot) && g.flares.length === 6, 'Pilot releases a six-flare burst');
check(heli.flareAmmo === 3 && heli.flareCd === 12, 'Burst consumes one charge and starts cooldown');
check(!decoyShot.target && decoyShot.decoy && !airThreat(g, heli), 'Incoming missile is redirected to a flare decoy');
check(g.snapshotFor(pilot).me.veh.flares[0] === 3 && g.snapshotFor(pilot).cf.length === 6, 'Charges and spatial flare snapshots reach clients');
check(!deployFlares(g, pilot) && heli.flareAmmo === 3, 'Repeated presses during cooldown cannot spend charges');
p.reloadT = p.fireCd = 0; p.gadget().loaded = true; lock(); check(!p.lockTarget, 'Active flare burst prevents reacquisition');
for (let i = 0; i < 240; i++) { g.time += DT; updateFlares(g, DT); updateProjectiles(g, DT); }
check(g.flares.length === 0 && heli.hp === heli.def.hp, 'Flares burn out and the decoyed missile misses the helicopter');
lock(); check(p.lockTarget === heli.id, 'Aircraft can be reacquired after flares expire');
selectSlot(g, p, 'primary'); check(!p.lockTarget, 'Switching weapons clears the seeker');
updateVehicles(g, 12); check(heli.flareCd === 0, 'Flare cooldown completes');
heli.flareAmmo = 0; check(!deployFlares(g, pilot), 'Empty flare dispenser refuses deployment');
heli.reset(g); check(heli.flareAmmo === 4 && heli.flareUntil === 0, 'Vehicle respawn restores countermeasures');
p.lockTarget = heli.id; p.lockT = AIR_DEFENSE.lockTime;
check(enterVehicle(g, p, heli, 0) && !p.lockTarget && !p.lockT, 'Boarding a vehicle clears the infantry seeker');
console.log(count, 'air defense checks passed');
