import assert from 'node:assert/strict';
import { Room } from '../src/server/room.js';
import { SPEC } from '../src/shared/constants.js';
const fake = () => ({ send() {}, sendRaw() {}, congested: () => false, leaveRoom() {} });
let count = 0;
const check = (value, message) => { assert.ok(value, message); count++; console.log('ok', message); };
for (const map of ['riverside', 'harbor', 'dunes']) {
  const room = new Room('ContestedQA', { map, mode: 'conquest', teamSize: 3, bots: false, vehicles: true }, null);
  const p = room.addHuman(fake(), 'Deploy'), enemy = room.addHuman(fake(), 'Enemy'), mate = room.addHuman(fake(), 'Squad');
  room.assignTeam(p, 0); room.assignTeam(enemy, 1); room.assignTeam(mate, 0); room.start();
  const g = room.game, f = g.flags.find((f) => f.owner === 0);
  p.respawnAt = g.time + .025;
  check(g.snapshotFor(p).rsp > 0 && !g.deploy(p, { k: 'base', id: p.team }), map + ' last respawn fraction stays disabled in the snapshot');
  p.respawnAt = g.time;
  check(g.snapshotFor(p).rsp === 0, map + ' timer reaches zero only when the server allows deployment');
  check(!!f, map + ' has a friendly deployment flag');
  const option = (k = 'flag', id = f.id) => g.spawnOptions(p).find((o) => o.k === k && o.id === id);
  check(option().ok, map + ' peaceful friendly flag is spawnable');
  enemy.alive = true; enemy.x = f.x; enemy.y = f.y; enemy.z = g.map.heightAt(f.x, f.y);
  check(!f.contested && !option().ok && option().why === 'Contested', map + ' enemy entry immediately blocks spawning before capture update');
  const pos = { x: p.x, y: p.y };
  check(!g.deploy(p, { k: 'flag', id: f.id }) && !p.alive && p.x === pos.x && p.y === pos.y, map + ' invalid flag request cannot fall back to base or another spawn');
  mate.alive = true; mate.x = f.x + 15; mate.y = f.y; mate.squad = p.squad; mate.lastHurt = -100;
  g.gadgets.push({ id: 999, type: 'beacon', team: p.team, squad: p.squad, x: f.x, y: f.y });
  check(!option('squad', mate.id).ok && !option('beacon', 999).ok, map + ' squad and beacon insertions cannot bypass a contested flag');
  g.mode.update(g, 1 / 60);
  check(f.contested && !option().ok, map + ' mixed friendly/enemy presence stays blocked');
  const owner = f.owner;
  f.owner = -1;
  check(!option('squad', mate.id).ok && !option('beacon', 999).ok, map + ' neutral contested flags also block squad and beacon insertion');
  f.owner = owner;
  enemy.alive = false; g.mode.update(g, 1 / 60);
  check(option().ok && option('beacon', 999).ok, map + ' dead enemies stop blocking deployment');
  enemy.alive = true; enemy.team = SPEC;
  check(option().ok, map + ' spectators do not contest deployment');
  enemy.team = 1; enemy.veh = g.vehicles.find((v) => v.type === 'heli').id;
  check(option().ok, map + ' aircraft overhead do not contest a ground flag');
  enemy.veh = g.vehicles.find((v) => v.type === 'jeep').id;
  check(!option().ok, map + ' enemy ground vehicle crews contest deployment');
  enemy.veh = 0; enemy.x = f.x + f.r + 5;
  check(option().ok && g.deploy(p, { k: 'flag', id: f.id }), map + ' deployment resumes after the capture zone is clear');
}
console.log(count, 'contested deployment checks passed');
