import assert from 'node:assert/strict';
import { Room } from '../src/server/room.js';
import { MapBuilder } from '../src/shared/maps/builder.js';
import { GameMap } from '../src/shared/gamemap.js';
import { VEHICLES, vehicleShot, stepVehicle } from '../src/shared/vehicles.js';
import { vehicleAimPoint, cylinderHit } from '../src/shared/vehicle-aim.js';
import { vehicleFire, vehicleCmd } from '../src/server/vehicles.js';
import { updateProjectiles } from '../src/server/projectiles.js';
const mb = new MapBuilder(50, 50, '.'); mb.rect(1, 1, 3, 3, 't').rect(45, 45, 3, 3, 'c');
const map = new GameMap({ id: 'controls', name: 'controls', ...mb.finish() });
const fake = () => ({ send() {}, sendRaw() {}, congested: () => false, leaveRoom() {} });
const room = new Room('VehicleQA', { map: 'riverside', mode: 'conquest', teamSize: 2, bots: false, vehicles: true }, null);
const p = room.addHuman(fake(), 'Driver'), q = room.addHuman(fake(), 'Target'); room.assignTeam(p, 0); room.assignTeam(q, 1); room.start();
const g = room.game; g.map = map; g.vehicles.forEach((v) => { v.map = map; });
for (const s of [p, q]) { s.respawnAt = 0; g.deploy(s, { k: 'base', id: 0 }); s.spawnProt = 0; }
let count = 0;
const check = (condition, message) => { assert.ok(condition, message); count++; console.log('ok', message); };
for (const id of ['quad', 'jeep', 'apc', 'tank', 'heli', 'boat']) {
  const def = VEHICLES[id], s = { x: 400, y: 400, a: 0, vx: 0, vy: 0 };
  const drivingMap = { moveCircle: (x, y, dx, dy) => ({ x: x + dx, y: y + dy }), blockBoat: map.blockBoat, blockInf: map.blockInf };
  for (let i = 0; i < 120; i++) stepVehicle(drivingMap, s, def, 1, 0);
  check(s.x > 450, id + ' accelerates forward');
  const speed = Math.hypot(s.vx, s.vy);
  for (let i = 0; i < 45; i++) stepVehicle(drivingMap, s, def, 512, 0);
  check(Math.hypot(s.vx, s.vy) < speed * .2, id + ' brake slows movement');
  for (let i = 0; i < 90; i++) stepVehicle(drivingMap, s, def, 2, 0);
  check(s.vx < -10, id + ' reverses');
}
check(cylinderHit(0, 0, 200, 1, 0, 0, 200, 0, 11, 0, 29, 400) < 0, 'High rays miss infantry underneath');
const hit = vehicleAimPoint(map, { x: 400, y: 400, z: 26 }, { x: 1, y: 0, z: 0 }, [{ x: 600, y: 400, z: 0 }], [], 0, []);
check(Math.abs(hit.x - 589) < .001 && hit.z === 26, 'Crosshair targets infantry at its actual height');
const high = vehicleAimPoint(map, { x: 400, y: 400, z: 220 }, { x: 1, y: 0, z: 0 }, [], [{ id: 9, ty: 0, x: 700, y: 400 }], 0, [VEHICLES.heli]);
check(high.x < 700 && high.z === 220, 'Crosshair targets airborne vehicle height');
const all = g.vehicles;
for (const id of ['tank', 'apc', 'heli']) {
  const v = all.find((v) => v.type === id); g.vehicles = [v]; v.x = 400; v.y = 400; v.a = v.ta = 0; v.seats[0] = p.id; v.cd[0] = v.rel[0] = 0;
  p.veh = v.id; p.seat = 0; q.x = 740; q.y = 400; q.z = 0; q.cf = 0; q.hp = 100; q.alive = true; q.spawnProt = 0;
  g.projectiles = []; vehicleFire(g, v, 0, p, true, 0, 340, 14);
  check(g.projectiles.length === 1 && Number.isFinite(g.projectiles[0].z), id + ' launches a 3D round from its barrel');
  for (let i = 0; i < 120 && g.projectiles.length; i++) updateProjectiles(g, 1 / 60);
  check(q.hp < 100, id + ' projectile hits infantry at crosshair height');
}
const v = all.find((v) => v.type === 'tank'); g.vehicles = [v]; v.x = 400; v.y = 400; v.ta = 0; v.a = 0; p.veh = v.id; p.seat = 0;
vehicleCmd(g, p, 0, .2, 0, 500, 180);
check(v.seatPitch[0] > .1, 'Barrel pitch follows elevated aim without firing');
const shot = vehicleShot(v, 0, v.ta, 500, 180);
const d = Math.hypot(shot.target.x - shot.x, shot.target.y - shot.y);
check(Math.abs(shot.z + Math.tan(shot.pitch) * d - 180) < .01, 'Barrel direction and authoritative ray converge at the same target');
g.projectiles = []; v.cd[0] = 0; vehicleFire(g, v, 0, p, true, 0, 500, 500);
q.x = 500; q.y = 400; q.hp = 100; q.alive = true;
for (let i = 0; i < 120 && g.projectiles.length; i++) updateProjectiles(g, 1 / 60);
check(q.hp === 100, 'High airborne detonation does not hurt infantry directly below');
v.x = 480; v.y = 440; v.ta = 0; p.veh = v.id; p.seat = 0;
q.x = 740; q.y = 400; q.hp = 100; q.alive = true; q.spawnProt = 0;
for (let i = 0; i < 60; i++) vehicleCmd(g, p, 0, 0, 0, 340, 14, { x: q.x, y: q.y });
check(Math.abs(v.ta - Math.atan2(-40, 260)) < .001, 'World target corrects aim after the vehicle moves sideways');
g.projectiles = []; v.cd[0] = 0; vehicleCmd(g, p, 16, 0, 0, 340, 14, { x: q.x, y: q.y });
for (let i = 0; i < 120 && g.projectiles.length; i++) updateProjectiles(g, 1 / 60);
check(q.hp < 100, 'Server fires at the same world target after vehicle movement');
v.x = v.y = 400; v.a = v.ta = v.seatAim[1] = 0; v.cd[1] = 0; p.seat = 1;
q.x = 740; q.y = 400; q.z = q.cf = 0; q.hp = 100; q.alive = true; q.spawnProt = 0; q.record(54); q.record(55);
q.y = 650; q.record(60); g.time = 1; g.tick = 60;
vehicleFire(g, v, 1, p, true, .9, 340, 14);
check(q.hp < 100, 'Mounted guns rewind moving infantry to the client view time');
const jeep = all.find((v) => v.type === 'jeep'); g.vehicles = [jeep];
jeep.x = jeep.y = 400; jeep.a = jeep.seatAim[1] = 0; jeep.cd[1] = jeep.rel[1] = 0; p.veh = jeep.id; p.seat = 1;
vehicleCmd(g, p, 0, Math.PI, 0, 7, 14, { x: 393, y: 400 });
check(Math.abs(jeep.seatAim[1]) < .001, 'A target in front of the jeep gun but behind the chassis center does not flip the gun backward');
const nearShot = vehicleShot(jeep, 1, jeep.seatAim[1], 7, 14, { x: 393, y: 400 });
check(Math.abs(nearShot.target.x - 393) < .01 && Math.cos(nearShot.yaw) > 0, 'Close gunner shots use the actual mount-to-target direction');
const skyMap = { castBullet: (...args) => ({ d: args[6] }) }, own = [{ id: 42, ty: 0, x: 0, y: 0 }];
const far = vehicleAimPoint(skyMap, { x: -180, y: 0, z: 250 }, { x: 1, y: 0, z: 0 }, [], own, 42, [VEHICLES.jeep], 2400, true);
const zoomed = vehicleAimPoint(skyMap, { x: 24, y: 0, z: 200 }, { x: far.x - 24, y: 0, z: far.z - 200 }, [], own, 42, [VEHICLES.jeep], 2400, true);
check(Math.hypot(zoomed.x - far.x, zoomed.z - far.z) < .01, 'Camera switching preserves distant gunner targets beyond terrain hits');
console.log(count, 'vehicle control and targeting checks passed');
